//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control
    {
        public int id { get; set; }
        public string tablename { get; set; }
        public string columnname { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string type { get; set; }
        public string labelname { get; set; }
    }
}
