//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eto_report
    {
        public int eid { get; set; }
        public string etoid { get; set; }
        public string projectname { get; set; }
        public string weirorderno { get; set; }
        public string customer { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> createduser { get; set; }
        public Nullable<System.DateTime> createdtm { get; set; }
        public Nullable<int> lastmoduser { get; set; }
        public Nullable<System.DateTime> lastmoddtm { get; set; }
        public string revision { get; set; }
        public string site { get; set; }
        public string childid { get; set; }
    }
}
