//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eto_hasrouting
    {
        public int etorelid { get; set; }
        public Nullable<int> etoeid { get; set; }
        public string hasrouting_itemid { get; set; }
        public string hasrouting_drawingid { get; set; }
        public string site { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> hasrouting_iid { get; set; }
    }
}
