//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etoitem_report
    {
        public int erid { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> hasgadrwng_iid { get; set; }
        public Nullable<int> hasdocument_iid { get; set; }
        public Nullable<int> hasrouting { get; set; }
        public Nullable<int> orderparts_iid { get; set; }
        public string references_iid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> createduser { get; set; }
        public Nullable<System.DateTime> createdtm { get; set; }
        public Nullable<int> lastmoduser { get; set; }
        public Nullable<System.DateTime> lastmoddtm { get; set; }
        public Nullable<int> hasga_drawingid { get; set; }
        public Nullable<int> hasrouting_drawingid { get; set; }
        public Nullable<int> hasdocument_drawingid { get; set; }
        public Nullable<int> orderparts_drawingid { get; set; }
        public Nullable<int> references_drawingid { get; set; }
    }
}
