//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_doc_references
    {
        public int idriid { get; set; }
        public Nullable<int> iid { get; set; }
        public string document_itemid { get; set; }
        public string site { get; set; }
        public int createduser { get; set; }
        public System.DateTime createdtm { get; set; }
        public int lastmoduser { get; set; }
        public System.DateTime lastmoddtm { get; set; }
        public int status { get; set; }
    }
}
