//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int iid { get; set; }
        public string itemid { get; set; }
        public string itemname { get; set; }
        public string description { get; set; }
        public string revision { get; set; }
        public string drawingid { get; set; }
        public string site { get; set; }
        public int createduser { get; set; }
        public System.DateTime createdtm { get; set; }
        public int lastmoduser { get; set; }
        public System.DateTime lastmoddtm { get; set; }
        public Nullable<int> updatedrefid { get; set; }
        public int status { get; set; }
        public Nullable<int> dcoid { get; set; }
        public string designatedprefpart { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public string erp_part_name { get; set; }
        public string erp_part_description { get; set; }
        public string material_code { get; set; }
        public Nullable<int> t4s_enabled { get; set; }
        public string datereleased { get; set; }
        public string aliasid { get; set; }
        public string altid { get; set; }
        public string drawing_revision { get; set; }
        public string legacy_part_number { get; set; }
        public string legacy_document_number { get; set; }
        public Nullable<int> itemtype { get; set; }
        public Nullable<int> itemstatus { get; set; }
        public string encumbrance { get; set; }
    }
}
