//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class led_iom_certificate
    {
        public int docid { get; set; }
        public string docname { get; set; }
        public string path { get; set; }
        public Nullable<int> docrefid { get; set; }
        public string doctype { get; set; }
        public string description { get; set; }
        public Nullable<int> createduser { get; set; }
        public Nullable<int> lastmoduser { get; set; }
        public Nullable<System.DateTime> createddtm { get; set; }
        public Nullable<System.DateTime> lastmoddtm { get; set; }
        public Nullable<int> toolid { get; set; }
        public string site { get; set; }
    }
}
