//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class led_ir
    {
        public int iid { get; set; }
        public string LEDItemID { get; set; }
        public string revision { get; set; }
        public string toolname { get; set; }
        public string description { get; set; }
        public Nullable<double> wll { get; set; }
        public Nullable<double> tare { get; set; }
        public int status { get; set; }
        public Nullable<int> createduser { get; set; }
        public Nullable<System.DateTime> createddtm { get; set; }
        public Nullable<int> lastmoduser { get; set; }
        public Nullable<System.DateTime> lastmoddtm { get; set; }
        public Nullable<int> tooltype { get; set; }
        public Nullable<int> toolstatus { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public string dco { get; set; }
        public string drawingid { get; set; }
        public string site { get; set; }
    }
}
