//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcnitem_report
    {
        public int prid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> problemitem_iid { get; set; }
        public Nullable<int> solutionitem_iid { get; set; }
        public Nullable<int> impacteditem_iid { get; set; }
        public Nullable<int> createduser { get; set; }
        public Nullable<System.DateTime> createdtm { get; set; }
        public Nullable<int> lastmoduser { get; set; }
        public Nullable<System.DateTime> lastmoddtm { get; set; }
        public Nullable<int> status { get; set; }
    }
}
