//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ProductOwnerId { get; set; }
        public string ProductOwnerEmail { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
