//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class useractivity
    {
        public int id { get; set; }
        public string refcategoryid { get; set; }
        public string refid { get; set; }
        public string action { get; set; }
        public string actionlink { get; set; }
        public Nullable<int> uid { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string description1 { get; set; }
        public string description { get; set; }
        public string browser { get; set; }
    }
}
