//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertype
    {
        public int utid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int createuser { get; set; }
        public System.DateTime createdtm { get; set; }
        public int lastmoduser { get; set; }
        public System.DateTime lastmoddtm { get; set; }
        public byte status { get; set; }
    }
}
